### ISSUE TITLE
Method Bucket.getEntries() crushes

### ISSUE THREAD

**Issue by flipback** [reduct-storage/reduct-js#12]
I got exception when I tried to use:

```
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at Function.parse (/home/atimin/Projects/flipback/reduct-storage/reduct-mqtt-example/node_modules/reduct-js/lib/cjs/EntryInfo.js:37:25)
    at /home/atimin/Projects/flipback/reduct-storage/reduct-mqtt-example/node_modules/reduct-js/lib/cjs/Bucket.js:55:82
    at Array.map (<anonymous>)
    at Bucket.getEntryList (/home/atimin/Projects/flipback/reduct-storage/reduct-mqtt-example/node_modules/reduct-js/lib/cjs/Bucket.js:55:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/atimin/Projects/flipback/reduct-storage/reduct-mqtt-example/reader.js:13:15
```

**Comment by flipback** [comment]
I used an old version of reduct storage
